<a href="https://colab.research.google.com/github/felicitymueni/Felicity-musau-Independent-project/blob/main/FELICITY_CHURN_PREDICTION_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DATA PREPARATION

Importing Libraries

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

Reading Data

In [ ]:
df=pd.read_csv('/content/Telco-Customer-Churn.csv')
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [ ]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
len(df)

7043

In [ ]:
df.head().T#transposes the first five rows to columns and columns to rows.

,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

In [ ]:
df.dtypes#returns the data types in the data frame

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [ ]:
df.TotalCharges

0         29.85
1        1889.5
2        108.15
3       1840.75
4        151.65
         ...
7038     1990.5
7039     7362.9
7040     346.45
7041      306.6
7042     6844.5
Name: TotalCharges, Length: 7043, dtype: object

In [ ]:
tc=pd.to_numeric(df.TotalCharges,errors='coerce')

In [ ]:
df[tc.isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [ ]:
df.totalcharges=pd.to_numeric(df.TotalCharges,errors='coerce')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.

In [ ]:
df.totalcharges=df.TotalCharges.fillna(0)

In [ ]:
df.totalcharges

0         29.85
1        1889.5
2        108.15
3       1840.75
4        151.65
         ...
7038     1990.5
7039     7362.9
7040     346.45
7041      306.6
7042     6844.5
Name: TotalCharges, Length: 7043, dtype: object

In [ ]:
df[tc.isnull()][['customerID','TotalCharges']]

      customerID TotalCharges
488   4472-LVYGI
753   3115-CZMZD
936   5709-LVOEQ
1082  4367-NUYAO
1340  1371-DWPAZ
3331  7644-OMVMY
3826  3213-VVOLG
4380  2520-SGTTA
5218  2923-ARZLG
6670  4075-WKNIU
6754  2775-SEFEE

In [ ]:
df.Churn#gives yes or no prediction on the dataframe values

0        No
1        No
2       Yes
3        No
4       Yes
       ...
7038     No
7039     No
7040     No
7041    Yes
7042     No
Name: Churn, Length: 7043, dtype: object

In [ ]:
df.Churn.head()

0     No
1     No
2    Yes
3     No
4    Yes
Name: Churn, dtype: object

In [ ]:
df.Churn=='yes'

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Name: Churn, Length: 7043, dtype: bool

In [ ]:
(df.Churn=='yes').head()

0    False
1    False
2    False
3    False
4    False
Name: Churn, dtype: bool

In [ ]:
(df.Churn=='yes').astype(int).head()#converting the churn variable to binary vriable

0    0
1    0
2    0
3    0
4    0
Name: Churn, dtype: int64

Setting up the validation framework

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
train_test_split?

In [ ]:
train_test_split(df,test_size=0.2,random_state=1)#split the data frame into two arrays the train and test subsets

[      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
 1814  5442-PPTJY    Male              0     Yes        Yes      12
 5946  6261-RCVNS  Female              0      No         No      42
 3881  2176-OSJUV    Male              0     Yes         No      71
 2389  6161-ERDGD    Male              0     Yes        Yes      71
 3676  2364-UFROM    Male              0      No         No      30
 ...          ...     ...            ...     ...        ...     ...
 905   0781-LKXBR    Male              1      No         No       9
 5192  3507-GASNP    Male              0      No        Yes      60
 3980  8868-WOZGU    Male              0      No         No      28
 235   1251-KRREG    Male              0      No         No       2
 5157  5840-NVDCG  Female              0     Yes        Yes      16

      PhoneService MultipleLines InternetService       OnlineSecurity  ...  \
 1814          Yes            No              No  No internet service  ...
 5946          Yes            No             DSL                  Yes  ...
 3881          Yes           Yes             DSL                  Yes  ...
 2389          Yes           Yes             DSL                  Yes  ...
 3676          Yes            No             DSL                  Yes  ...
 ...           ...           ...             ...                  ...  ...
 905           Yes           Yes     Fiber optic                   No  ...
 5192          Yes            No              No  No internet service  ...
 3980          Yes           Yes     Fiber optic                   No  ...
 235           Yes           Yes             DSL                   No  ...
 5157          Yes            No             DSL                  Yes  ...

          DeviceProtection          TechSupport          StreamingTV  \
 1814  No internet service  No internet service  No internet service
 5946                  Yes                  Yes                   No
 3881                   No                  Yes                   No
 2389                  Yes                  Yes                  Yes
 3676                   No                  Yes                  Yes
 ...                   ...                  ...                  ...
 905                   Yes                   No                  Yes
 5192  No internet service  No internet service  No internet service
 3980                  Yes                   No                  Yes
 235                    No                   No                   No
 5157                   No                  Yes                   No

           StreamingMovies        Contract PaperlessBilling  \
 1814  No internet service        Two year               No
 5946                  Yes        One year               No
 3881                   No        Two year               No
 2389                  Yes        One year               No
 3676                   No        One year               No
 ...                   ...             ...              ...
 905                   Yes  Month-to-month              Yes
 5192  No internet service        Two year               No
 3980                  Yes  Month-to-month              Yes
 235                    No  Month-to-month              Yes
 5157                  Yes        Two year               No

                   PaymentMethod MonthlyCharges  TotalCharges Churn
 1814               Mailed check          19.70        258.35    No
 5946    Credit card (automatic)          73.90       3160.55   Yes
 3881  Bank transfer (automatic)          65.15       4681.75    No
 2389           Electronic check          85.45       6300.85    No
 3676           Electronic check          70.40       2044.75    No
 ...                         ...            ...           ...   ...
 905            Electronic check         100.50         918.6   Yes
 5192               Mailed check          19.95        1189.9    No
 3980           Electronic check         105.70        2979.5   Yes
 235                Mailed check          54.40         114.1   Yes
 5157  Bank transfer (automatic)          68.25       1114.85    No

 [5634 rows x 21 columns],
       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
 3381  8879-ZKJOF  Female              0      No         No      41
 6180  0201-MIBOL  Female              1      No         No      66
 4829  1600-DILPE  Female              0      No         No      12
 3737  8601-QACRS  Female              0      No         No       5
 4249  7919-ZODZZ  Female              0     Yes        Yes      10
 ...          ...     ...            ...     ...        ...     ...
 2563  5130-IEKQT    Male              1      No         No      25
 2028  4452-ROHMO  Female              0      No         No      15
 2899  6164-HAQTX    Male              0      No         No      71
 3474  3982-DQLUS    Male              1     Yes        Yes      65
 5154  9874-QLCLH  Female              0     Yes        Yes      17

      PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
 3381          Yes                No             DSL                  Yes  ...
 6180          Yes               Yes     Fiber optic                  Yes  ...
 4829          Yes                No             DSL                   No  ...
 3737          Yes               Yes             DSL                   No  ...
 4249          Yes                No             DSL                   No  ...
 ...           ...               ...             ...                  ...  ...
 2563          Yes               Yes     Fiber optic                   No  ...
 2028          Yes                No              No  No internet service  ...
 2899           No  No phone service             DSL                  Yes  ...
 3474          Yes               Yes     Fiber optic                  Yes  ...
 5154          Yes               Yes     Fiber optic                  Yes  ...

          DeviceProtection          TechSupport          StreamingTV  \
 3381                  Yes                  Yes                  Yes
 6180                   No                   No                  Yes
 4829                   No                   No                   No
 3737                   No                   No                   No
 4249                  Yes                   No                   No
 ...                   ...                  ...                  ...
 2563                  Yes                   No                  Yes
 2028  No internet service  No internet service  No internet service
 2899                  Yes                  Yes                  Yes
 3474                   No                   No                   No
 5154                  Yes                   No                  Yes

           StreamingMovies        Contract PaperlessBilling  \
 3381                  Yes        One year              Yes
 6180                  Yes        Two year              Yes
 4829                   No  Month-to-month              Yes
 3737                   No  Month-to-month              Yes
 4249                  Yes        One year              Yes
 ...                   ...             ...              ...
 2563                  Yes  Month-to-month               No
 2028  No internet service        Two year               No
 2899                   No        Two year               No
 3474                   No  Month-to-month              Yes
 5154                  Yes  Month-to-month              Yes

                   PaymentMethod MonthlyCharges  TotalCharges Churn
 3381  Bank transfer (automatic)          79.85       3320.75    No
 6180  Bank transfer (automatic)         102.40       6471.85    No
 4829  Bank transfer (automatic)          45.00        524.35    No
 3737               Mailed check          50.60        249.95   Yes
 4249               Mailed check          65.90        660.05    No
 ...                         ...            ...           ...   ...
 2563               Mailed check         105.95       2655.25   Yes
 2028               Mailed check          19.60         331.6    No
 2899  Bank transfer (automatic)          53.95       3888.65    No
 3474           Electronic check          85.75       5688.45    No
 5154           Electronic check         104.20        1743.5   Yes

 [1409 rows x 21 columns]]

In [ ]:
df_full_train,df_test=train_test_split(df,test_size=0.2,random_state=1)

In [ ]:
len(df_full_train),len(df_test)

(5634, 1409)

In [ ]:
df_train,df_val=train_test_split(df_full_train,test_size=0.25,random_state=1)

In [ ]:
len(df_train),len(df_val),len(df_test)#returns number of values in the container

(4225, 1409, 1409)

In [ ]:
df_train

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
3897,8015-IHCGW,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,115.50,8425.15,No
1980,1960-UYCNN,Male,0,No,No,10,Yes,Yes,Fiber optic,No,...,Yes,No,No,Yes,Month-to-month,Yes,Electronic check,95.25,1021.55,No
6302,9250-WYPLL,Female,0,No,No,5,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,No,Electronic check,75.55,413.65,Yes
727,6786-OBWQR,Female,0,Yes,Yes,5,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,80.85,356.1,No
5104,1328-EUZHC,Female,0,Yes,No,18,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.10,370.5,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3774,1309-XGFSN,Male,1,Yes,Yes,52,Yes,Yes,DSL,No,...,Yes,No,Yes,Yes,One year,Yes,Electronic check,80.85,4079.55,No
6108,4819-HJPIW,Male,0,No,No,18,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,No,Mailed check,25.15,476.8,No
1530,3703-VAVCL,Male,0,Yes,Yes,2,Yes,No,Fiber optic,No,...,Yes,Yes,No,Yes,Month-to-month,No,Credit card (automatic),90.00,190.05,Yes
3701,3812-LRZIR,Female,0,Yes,Yes,27,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Electronic check,24.50,761.95,No
4368,1704-NRWYE,Female,1,No,No,9,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,80.85,751.65,Yes

In [ ]:
df_train.reset_index(drop=True)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,8015-IHCGW,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,115.50,8425.15,No
1,1960-UYCNN,Male,0,No,No,10,Yes,Yes,Fiber optic,No,...,Yes,No,No,Yes,Month-to-month,Yes,Electronic check,95.25,1021.55,No
2,9250-WYPLL,Female,0,No,No,5,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,No,Electronic check,75.55,413.65,Yes
3,6786-OBWQR,Female,0,Yes,Yes,5,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,80.85,356.1,No
4,1328-EUZHC,Female,0,Yes,No,18,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.10,370.5,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4220,1309-XGFSN,Male,1,Yes,Yes,52,Yes,Yes,DSL,No,...,Yes,No,Yes,Yes,One year,Yes,Electronic check,80.85,4079.55,No
4221,4819-HJPIW,Male,0,No,No,18,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,No,Mailed check,25.15,476.8,No
4222,3703-VAVCL,Male,0,Yes,Yes,2,Yes,No,Fiber optic,No,...,Yes,Yes,No,Yes,Month-to-month,No,Credit card (automatic),90.00,190.05,Yes
4223,3812-LRZIR,Female,0,Yes,Yes,27,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Electronic check,24.50,761.95,No
4224,1704-NRWYE,Female,1,No,No,9,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,80.85,751.65,Yes

In [ ]:
df_train=df_train.reset_index(drop=True)
df_val=df_val.reset_index(drop=True)
df_test=df_test.reset_index(drop=True)

In [ ]:
y_train=df_train.Churn.values
y_val=df_val.Churn.values
y_test=df_test.Churn.values

In [ ]:
del df_train['Churn']
del df_val['Churn']
del df_test['Churn']

# EXPLANATORY DATA ANALYSIS

Finding missing values

In [ ]:
df_full_train

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
1814,5442-PPTJY,Male,0,Yes,Yes,12,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.70,258.35,No
5946,6261-RCVNS,Female,0,No,No,42,Yes,No,DSL,Yes,...,Yes,Yes,No,Yes,One year,No,Credit card (automatic),73.90,3160.55,Yes
3881,2176-OSJUV,Male,0,Yes,No,71,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,No,Bank transfer (automatic),65.15,4681.75,No
2389,6161-ERDGD,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,No,Electronic check,85.45,6300.85,No
3676,2364-UFROM,Male,0,No,No,30,Yes,No,DSL,Yes,...,No,Yes,Yes,No,One year,No,Electronic check,70.40,2044.75,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
905,0781-LKXBR,Male,1,No,No,9,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.50,918.6,Yes
5192,3507-GASNP,Male,0,No,Yes,60,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.95,1189.9,No
3980,8868-WOZGU,Male,0,No,No,28,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,105.70,2979.5,Yes
235,1251-KRREG,Male,0,No,No,2,Yes,Yes,DSL,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,54.40,114.1,Yes
5157,5840-NVDCG,Female,0,Yes,Yes,16,Yes,No,DSL,Yes,...,No,Yes,No,Yes,Two year,No,Bank transfer (automatic),68.25,1114.85,No

In [ ]:
df_full_train=df_full_train.reset_index(drop=True)

In [ ]:
df_full_train.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
df_full_train.Churn

0        No
1       Yes
2        No
3        No
4        No
       ...
5629    Yes
5630     No
5631    Yes
5632    Yes
5633     No
Name: Churn, Length: 5634, dtype: object

In [ ]:
df_full_train.Churn.value_counts()#returns a series containing counts of same values

No     4113
Yes    1521
Name: Churn, dtype: int64

In [ ]:
df_full_train.Churn.value_counts(normalize=True)# churn rate at which the churn is used in the dataset

No     0.730032
Yes    0.269968
Name: Churn, dtype: float64

In [77]:
df_full_train.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [78]:
numerical=['tenure','MonthlyCharges','TotalCharges']

In [79]:
df_full_train.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [81]:
categorical=['gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod',]

In [82]:
df_full_train[categorical]

,gender,SeniorCitizen,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod
0,Male,0,Yes,Yes,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check
1,Female,0,No,No,Yes,No,DSL,Yes,Yes,Yes,Yes,No,Yes,One year,No,Credit card (automatic)
2,Male,0,Yes,No,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,No,Bank transfer (automatic)
3,Male,0,Yes,Yes,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,No,Electronic check
4,Male,0,No,No,Yes,No,DSL,Yes,Yes,No,Yes,Yes,No,One year,No,Electronic check
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5629,Male,1,No,No,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check
5630,Male,0,No,Yes,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check
5631,Male,0,No,No,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check
5632,Male,0,No,No,Yes,Yes,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Mailed check
5633,Female,0,Yes,Yes,Yes,No,DSL,Yes,Yes,No,Yes,No,Yes,Two year,No,Bank transfer (automatic)

In [83]:
df_full_train[categorical].nunique()#number of unique values in each column

gender              2
SeniorCitizen       2
Partner             2
Dependents          2
PhoneService        2
MultipleLines       3
InternetService     3
OnlineSecurity      3
OnlineBackup        3
DeviceProtection    3
TechSupport         3
StreamingTV         3
StreamingMovies     3
Contract            3
PaperlessBilling    2
PaymentMethod       4
dtype: int64

# Feature Importance:Churn rate and Risk ratio

Churn Rate

In [84]:
df_full_train.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,5442-PPTJY,Male,0,Yes,Yes,12,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.70,258.35,No
1,6261-RCVNS,Female,0,No,No,42,Yes,No,DSL,Yes,...,Yes,Yes,No,Yes,One year,No,Credit card (automatic),73.90,3160.55,Yes
2,2176-OSJUV,Male,0,Yes,No,71,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,No,Bank transfer (automatic),65.15,4681.75,No
3,6161-ERDGD,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,No,Electronic check,85.45,6300.85,No
4,2364-UFROM,Male,0,No,No,30,Yes,No,DSL,Yes,...,No,Yes,Yes,No,One year,No,Electronic check,70.40,2044.75,No

In [85]:
df_full_train[df_full_train.gender=='Female']

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
1,6261-RCVNS,Female,0,No,No,42,Yes,No,DSL,Yes,...,Yes,Yes,No,Yes,One year,No,Credit card (automatic),73.90,3160.55,Yes
5,4765-OXPPD,Female,0,Yes,Yes,9,Yes,No,DSL,Yes,...,Yes,Yes,No,No,Month-to-month,No,Mailed check,65.00,663.05,Yes
9,1732-VHUBQ,Female,1,Yes,Yes,47,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,No,Bank transfer (automatic),70.55,3309.25,Yes
11,7017-VFULY,Female,0,Yes,No,2,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Bank transfer (automatic),20.10,43.15,No
13,1374-DMZUI,Female,1,No,No,4,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,94.30,424.45,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5618,8065-YKXKD,Female,0,No,No,10,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,74.75,799.65,Yes
5619,5627-TVBPP,Female,0,No,Yes,35,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Credit card (automatic),20.10,644.5,No
5626,3262-EIDHV,Female,0,Yes,Yes,72,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),84.70,5893.9,No
5627,7446-SFAOA,Female,0,Yes,No,37,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Bank transfer (automatic),19.85,717.5,No
5633,5840-NVDCG,Female,0,Yes,Yes,16,Yes,No,DSL,Yes,...,No,Yes,No,Yes,Two year,No,Bank transfer (automatic),68.25,1114.85,No

In [86]:
df_full_train[df_full_train.gender=='Female'].Churn

1       Yes
5       Yes
9       Yes
11       No
13      Yes
       ...
5618    Yes
5619     No
5626     No
5627     No
5633     No
Name: Churn, Length: 2796, dtype: object

In [88]:
df_full_train[df_full_train.gender=='Female'].Churn.mean

<bound method NDFrame._add_numeric_operations.<locals>.mean of 1       Yes
5       Yes
9       Yes
11       No
13      Yes
       ...
5618    Yes
5619     No
5626     No
5627     No
5633     No
Name: Churn, Length: 2796, dtype: object>

In [91]:
df_full_train.Partner.value_counts()

No     2932
Yes    2702
Name: Partner, dtype: int64